FROM scratch
EXPOSE 8080
COPY TGV /
ENTRYPOINT ["/TGV"]

# docker run --rm -v /var/sources/TGV:/src centurylink/golang-builder &&\
# cp /var/sources/TGV/TGV /var/sources/docker.io/vincentserpoul/tgv/  &&\
# docker build -t vincentserpoul/tgv /var/sources/docker.io/vincentserpoul/tgv/  &&\
# docker push vincentserpoul/tgv
