# Build redis from source
# Make sure you have the redis source code checked out in
# the same directory as this Dockerfile

FROM dockerfile/redis:latest

MAINTAINER Vincent Serpoul <vincent@serpoul.com>

EXPOSE 6380 6381

# docker build -t vincentserpoul/redis .
# docker run --name myredis -p 6378:6378 -p 6379:6379 -p 6380:6380 -v /home/core/docker.io/vincentserpoul/docker_redis/shared/redis_data:/redis_data -v /home/core/docker.io/vincentserpoul/docker_redis/shared/redis_log:/var/log/redis -d vincentserpoul/redis
